@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api
@baseUrlWithoutApi = https://localhost:7002

### register
POST {{baseUrl}}/authentication/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Johnson",
    "email": "john@john.com",
    "password": "pass123@!"
}

### login
# @name login
POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
    "email": "john@john.com",
    "password": "pass123@!"
}

### token
@token = {{login.response.body.$.token}}

### random endpoint
GET {{baseUrl}}/WeatherForecast
Authorization: Bearer {{token}}

### random page
GET {{baseUrlWithoutApi}}/delivery
Cookie: OnibiAuth={{token}}

###
POST {{baseUrl}}/WeatherForecast/set/dupa/1234

###
GET {{baseUrl}}/WeatherForecast/get/dupa

###
POST {{baseUrl}}/authentication/logout
Authorization: Bearer {{token}}

###
GET https://localhost:7002/api/Authentication/isAuthenticated?3242432