@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api
@baseUrlWithoutApi = https://localhost:7002

### login
# @name login
POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
    "email": "globalManager@mcDowel.com",
    "password": "pass123@!"
}

### token
@token = {{login.response.body.$.token}}

### random endpoint
GET {{baseUrl}}/WeatherForecast
Authorization: Bearer {{token}}

### random page
GET {{baseUrlWithoutApi}}/delivery
Cookie: OnibiAuth={{token}}

###
POST {{baseUrl}}/authentication/logout
Authorization: Bearer {{token}}

###
GET https://localhost:7002/api/Authentication/isAuthenticated?3242432

###
POST {{baseUrl}}/account/register
Content-Type: application/json

{
    "username":"string",
    "password":"ssasa",
    "email": "dfdfsdf"
}

### confirm email
PUT {{baseUrl}}/authentication/ConfirmEmail/mxqmM1b1xKVQNOUdguALW1ej5D5i5+ENPqA06V2iOJnnCJJXEMjrEiWaxbDlzmMlIcr7gxkmWj9Q4uzyo8vPQQ==
