@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTUyZWIyZi1hOWRmLTRmODAtYTIwYy1hODg1NTA0OTAyMTQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiSm9obnNvbiIsImVtYWlsIjoiam9oblJlZ2lvbmFsTWFuYWdlckBqb2huLmNvbSIsIlVTRVJfVFlQRSI6IlJFR0lPTkFMTUFOQUdFUiIsImp0aSI6Ijk5ZGQ2ODkxLWM0NTMtNDhmOS05ZTMwLTllZjFkNThkZTFkYSIsImV4cCI6MTcwMzAyMDgwNiwiaXNzIjoiT25pYmlQcm8iLCJhdWQiOiJPbmliaVBybyJ9.JtSoXXaaAMR8293J1QvV8OfmKWyC8cGZTbqTuPEB6zc

### get manager details
GET {{baseUrl}}/identity/managerDetails/F59CF698-6F65-4902-8593-87E790931CBF
Content-Type: application/json
Authorization: Bearer {{token}}

### whoami
GET {{baseUrl}}/identity/whoami
Content-Type: application/json
Authorization: Bearer {{token}}
