@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

### create
POST {{baseUrl}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Street Food Craze",
  "MenuItems": [
    {
      "Name": "Spicy Beef Taco",
      "Price": 2.99,
      "Ingredients": [
        {
          "Name": "Beef Mince",
          "Unit": "Grams",
          "Quantity": 120
        },
        {
          "Name": "Taco Shell",
          "Unit": "Pieces",
          "Quantity": 1
        },
        {
          "Name": "Jalapenos",
          "Unit": "Pieces",
          "Quantity": 5
        },
        {
          "Name": "Shredded Lettuce",
          "Unit": "Grams",
          "Quantity": 30
        },
        {
          "Name": "Grated Cheese",
          "Unit": "Grams",
          "Quantity": 40
        },
        {
          "Name": "Sour Cream",
          "Unit": "Milliliters",
          "Quantity": 20
        }
      ]
    },
    {
      "Name": "Giant Meatball Sub",
      "Price": 6.49,
      "Ingredients": [
        {
          "Name": "Meatballs",
          "Unit": "Pieces",
          "Quantity": 4
        },
        {
          "Name": "Marinara Sauce",
          "Unit": "Milliliters",
          "Quantity": 60
        },
        {
          "Name": "Provolone Cheese",
          "Unit": "Pieces",
          "Quantity": 2
        },
        {
          "Name": "Sub Roll",
          "Unit": "Pieces",
          "Quantity": 1
        },
        {
          "Name": "Parmesan Cheese",
          "Unit": "Grams",
          "Quantity": 15
        }
      ]
    },
    {
      "Name": "BBQ Pulled Pork Sandwich",
      "Price": 5.99,
      "Ingredients": [
        {
          "Name": "Pulled Pork",
          "Unit": "Grams",
          "Quantity": 150
        },
        {
          "Name": "BBQ Sauce",
          "Unit": "Milliliters",
          "Quantity": 50
        },
        {
          "Name": "Coleslaw",
          "Unit": "Grams",
          "Quantity": 70
        },
        {
          "Name": "Sandwich Bun",
          "Unit": "Pieces",
          "Quantity": 1
        }
      ]
    },
    {
      "Name": "Fried Chicken Wings",
      "Price": 4.99,
      "Ingredients": [
        {
          "Name": "Chicken Wings",
          "Unit": "Pieces",
          "Quantity": 5
        },
        {
          "Name": "Flour",
          "Unit": "Grams",
          "Quantity": 50
        },
        {
          "Name": "Hot Sauce",
          "Unit": "Milliliters",
          "Quantity": 30
        },
        {
          "Name": "Butter",
          "Unit": "Grams",
          "Quantity": 20
        }
      ]
    }
  ]
}

### login
# @name login
POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
    "email": "globalManager@mcDowel.com",
    "password": "pass123@!"
}

### token
@token = {{login.response.body.$.token}}


### get
GET {{baseUrl}}/Menus
Authorization: Bearer {{token}}

