@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZjI3ZmQ1YS1mNDQyLTQwNDQtODBiYS04MWVlNjdkN2FiZjYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiSm9obnNvbiIsImVtYWlsIjoiam9obkBqb2huLmNvbSIsImp0aSI6IjhmZTFhNjQwLThhNDUtNDVhOC05OTgzLWQ5MjFkYzFlYzA0MyIsImV4cCI6MTcwMjIyNDUwMSwiaXNzIjoiT25pYmlQcm8iLCJhdWQiOiJPbmliaVBybyJ9.L1k5FbOZxn0T4KHY5L0hvAAGTKZDAVAWOOU53LXKpV4

### create
POST {{baseUrl}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Special Menu",
  "MenuItems": [
    {
      "Name": "Burger",
      "Price": 5.99,
      "Ingredients": [
        {
          "Name": "Beef Patty",
          "Unit": "Grams",
          "Quantity": 150
        },
        {
          "Name": "Cheese",
          "Unit": "Pieces",
          "Quantity": 1
        },
        {
          "Name": "Lettuce",
          "Unit": "Pieces",
          "Quantity": 2
        },
        {
          "Name": "Tomato",
          "Unit": "Pieces",
          "Quantity": 1
        }
      ]
    },
    {
      "Name": "Fries",
      "Price": 2.49,
      "Ingredients": [
        {
          "Name": "Potatoes",
          "Unit": "Grams",
          "Quantity": 200
        },
        {
          "Name": "Salt",
          "Unit": "Grams",
          "Quantity": 1
        }
      ]
    }
  ]
}
