@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNDg2Y2MzNy01YTExLTRmNmQtOGQwMi00MzkyMGZlMjc5MzMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiSm9obnNvbiIsImVtYWlsIjoiam9obkBqb2huLmNvbSIsImp0aSI6IjI0ZTI5YjBmLTNlMmUtNGQ3My1iMDA0LWQxNTZjYTEyNTczNSIsImV4cCI6MTcwMTgxNjQzNSwiaXNzIjoiT25pYmlQcm8iLCJhdWQiOiJPbmliaVBybyJ9.rWWjmuasojIlM4pdeip03sTpIbuzdPRTU2Rtx3fAcaA

### create
POST {{baseUrl}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Special Menu",
  "MenuItems": [
    {
      "Name": "Burger",
      "Price": 5.99,
      "Ingredients": [
        {
          "Name": "Beef Patty",
          "Unit": "Grams",
          "Quantity": 150
        },
        {
          "Name": "Cheese",
          "Unit": "Pieces",
          "Quantity": 1
        },
        {
          "Name": "Lettuce",
          "Unit": "Pieces",
          "Quantity": 2
        },
        {
          "Name": "Tomato",
          "Unit": "Pieces",
          "Quantity": 1
        }
      ]
    },
    {
      "Name": "Fries",
      "Price": 2.49,
      "Ingredients": [
        {
          "Name": "Potatoes",
          "Unit": "Grams",
          "Quantity": 200
        },
        {
          "Name": "Salt",
          "Unit": "Grams",
          "Quantity": 1
        }
      ]
    }
  ]
}
