@baseUrl =  https://localhost:7002/api

### login
# @name login
POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
    "email": "john@john.com",
    "password": "pass123@!"
}

### token
@token = {{login.response.body.$.token}}

### order by id
GET {{baseUrl}}/Orders/3E1F3691-902F-44BC-B409-20BBA7AF3A62
Authorization: Bearer {{token}}

### order by id wrong id
GET {{baseUrl}}/Orders/2B750804-E65E-43D7-BAC1-B43B6757DC32
Authorization: Bearer {{token}}

### create
POST {{baseUrl}}/Orders/E2E115CF-4A20-40E4-ADD5-67CF34788A0A
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "OrderItems": [
        {
            "Quantity": 12,
            "MenuItemId": "038C4A1F-D524-4461-8FB3-1183EBB627DC"
        },
        {
            "Quantity": 1,
            "MenuItemId": "E0708EC6-EE40-4042-B94C-5A7A1745D40E"
        }
    ]
}

### create invalid numbers
POST {{baseUrl}}/Orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "OrderItems": [
        {
            "Quantity": 12,
            "MenuItemId": "938BF590-D97E-418C-9460-8331C6AC8727"
        },
        {
            "Quantity": 1,
            "MenuItemId": "27466114-A8DA-4922-86B2-A6559EAE20EF"
        }
    ]
}

### get orders
GET {{baseUrl}}/Orders?startrow=2&amount=1
Content-Type: application/json
Authorization: Bearer {{token}}