@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNTljZjY5OC02ZjY1LTQ5MDItODU5My04N2U3OTA5MzFjYmYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiSm9obnNvbiIsImVtYWlsIjoiam9obkBqb2huLmNvbSIsIlVTRVJfVFlQRSI6Ik1BTkFHRVIiLCJqdGkiOiJiNmU4NTNlMS0yZjcxLTQ4ZmItYTkzZC1jMWNkNTJjYTA1NzkiLCJleHAiOjE3MDI5NTE3MTIsImlzcyI6Ik9uaWJpUHJvIiwiYXVkIjoiT25pYmlQcm8ifQ.sjM231sLs_ei9L4F2g6xToAxXFOhdkgrzelJH4BrTuQ

### create
POST {{baseUrl}}/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Address": {
    "Street": "123 Main Street",
    "City": "Anytown",
    "PostalCode": "12345",
    "Country": "USA"
  },
  "OrderIds": ["2B750804-E65E-43D7-BAC1-B43B6757DC31"],
  "Employees": [
    {
      "FirstName": "John",
      "LastName": "Doe",
      "Email": "john.doe@example.com",
      "EmployeePositions": [
        { "Position": "Cashier" },
        { "Position": "Cook" }
      ]
    },
    {
      "FirstName": "Jane",
      "LastName": "Smith",
      "Email": "jane.smith@example.com",
      "EmployeePositions": [
        { "Position": "Server" },
        { "Position": "Cleaner" }
      ]
    }
  ],
  "Managers": [
    {
      "FirstName": "Manager",
      "LastName": "One",
      "Email": "manager.one@example.com"
    },
    {
      "FirstName": "Manager",
      "LastName": "Two",
      "Email": "manager.two@example.com"
    }
  ]
}

### employees
GET {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/employees?FirstNameFilter=Donald
Authorization: Bearer {{token}}


### employees
POST {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "FirstName": "Alice",
  "LastName": "Wonderchef",
  "Email": "alice.wonderf@example.com",
  "City": "Foodsville",
  "EmployeePositions": ["Cashier", "Cook", "Server"]
}

### edit employees
PUT {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "EmployeeId": "12c7fea3-ee9b-47fc-9409-f1dc3f82a41a",
  "FirstName": "Donald",
  "LastName": "Trump",
  "Email": "realtrump@example.com",
  "City": "Foodsville",
  "EmployeePositions": ["Cook", "Server"]
}


### assign manager
POST {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/manager
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserId": "E7A4344B-6141-422D-9F61-5421958ED8B4"
}