@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNTljZjY5OC02ZjY1LTQ5MDItODU5My04N2U3OTA5MzFjYmYiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiSm9obnNvbiIsImVtYWlsIjoiam9obkBqb2huLmNvbSIsIlVTRVJfVFlQRSI6IlJFR0lPTkFMTUFOQUdFUiIsImp0aSI6ImI0ZDNiNjNkLWM0ODItNDM4Yy1hYWZlLTk4NDEwNTU2ZjFhNyIsIkNMSUVOVF9OQU1FIjoiTWNEb3dlbCIsImV4cCI6MTcwMzU1MDE0NywiaXNzIjoiT25pYmlQcm8iLCJhdWQiOiJPbmliaVBybyJ9.T8G_RpQIky3K3ilAUa-tqkxhUSekEZ2eeeyXZ5m_0Dk

### create
POST {{baseUrl}}/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Address": {
    "Street": "123 Main Street",
    "City": "Anytown",
    "PostalCode": "12345",
    "Country": "USA"
  },
  "OrderIds": ["2B750804-E65E-43D7-BAC1-B43B6757DC31"],
  "Employees": [
    {
      "FirstName": "John",
      "LastName": "Doe",
      "Email": "john.doe@example.com",
      "EmployeePositions": [
        { "Position": "Cashier" },
        { "Position": "Cook" }
      ]
    },
    {
      "FirstName": "Jane",
      "LastName": "Smith",
      "Email": "jane.smith@example.com",
      "EmployeePositions": [
        { "Position": "Server" },
        { "Position": "Cleaner" }
      ]
    }
  ],
  "Managers": [
    {
      "FirstName": "Manager",
      "LastName": "One",
      "Email": "manager.one@example.com"
    },
    {
      "FirstName": "Manager",
      "LastName": "Two",
      "Email": "manager.two@example.com"
    }
  ]
}

### employees
GET {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/employees?FirstNameFilter=Donald
Authorization: Bearer {{token}}


### employees
POST {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "FirstName": "Alice",
  "LastName": "Wonderchef",
  "Email": "alice.wonderf@example.com",
  "City": "Foodsville",
  "EmployeePositions": ["Cashier", "Cook", "Server"]
}

### edit employees
PUT {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "EmployeeId": "12c7fea3-ee9b-47fc-9409-f1dc3f82a41a",
  "FirstName": "Donald",
  "LastName": "Trump",
  "Email": "realtrump@example.com",
  "City": "Foodsville",
  "EmployeePositions": ["Cook", "Server"]
}


### assign manager
POST {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/manager
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserId": "FB90EB91-F251-4A07-9547-E26977341455"
}

### create schedule
POST {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/schedule
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "Test title2",
  "Priority": "Standard",
  "StartDate": "2012-04-23T18:25:43.511Z",
  "EndDate": "2012-04-23T18:25:43.511Z",
  "EmployeeIds": ["0F73E4D1-1030-4B4F-8BC8-3EABF743C991", "FCB5C1C2-2D58-4393-A20A-618CF76552E3"]
}

### get schedules
GET {{baseUrl}}/restaurants/E2E115CF-4A20-40E4-ADD5-67CF34788A0A/schedule
Content-Type: application/json
Authorization: Bearer {{token}}

### login
# @name login
POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
    "email": "john@john.com",
    "password": "pass123@!"
}

### token
@token = {{login.response.body.$.token}}