@baseUrl =  https://localhost:7002/api
#@baseUrl =  http://localhost:8080/api

### login
# @name login
POST {{baseUrl}}/authentication/login
Content-Type: application/json

{
    "email": "john@john.com",
    "password": "pass123@!"
}

### token
@token = {{login.response.body.$.token}}

### create package
POST {{baseUrl}}/shipments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Ingredients": [
    {"Name": "Milk", "Unit": "Milliliters", "Quantity": 1000},
    {"Name": "Choco", "Unit": "Grams", "Quantity": 2000},
    {"Name": "Pickles", "Unit": "Pieces", "Quantity": 4}
  ],
  "Until": "2023-01-01T12:00:00",
  "IsUrgent": true,
  "Message": "Please deliver ASAP"
}

### get
GET {{baseUrl}}/shipments/3de8acaf-8b12-4bbe-8997-b2565156afab
Content-Type: application/json
Authorization: Bearer {{token}}

### get all
GET {{baseUrl}}/shipments
Content-Type: application/json
Authorization: Bearer {{token}}